services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: DB_HOST
        value: your-planetscale-host
      - key: DB_USER
        value: your-username
      - key: DB_PASS
        value: your-password
      - key: DB_NAME
        value: your-dbname
